Elixir MQTT Client Macro
kopera/erlang-mqtt pull request #2
Opened 2017-04-10 05:58 UTC by erauer

Initial version of an Elixir MQTT client and a couple of tests for basic subscribe, publish and last will and testament.

The tests depend on an existing MQTT broker running locally

2017-04-10 08:05 UTC, asabil requested changes
Thank you for your contribution, this looks great and very much needed 👍 

I have left some comments, could you please have a look so we can get this landed.

2017-04-10 08:05 UTC, asabil commented on lib/mqtt/client.ex
> +      def init(_) do
I don't think the `init` callback is optional

2017-04-10 08:05 UTC, asabil commented on lib/mqtt/client.ex
> +          IO.puts("Macro handle connect")
Could you please remove this IO.puts

2017-04-10 08:05 UTC, asabil commented on lib/mqtt/client.ex
> +  defp convert_start_options(options) do
Maybe instead of doing this, we could change the underlying Erlang code to accept `iodata`for the host?

2017-04-10 17:10 UTC, erauer commented
@asabil, I'm happy to help. The library looks great so far, I'm glad to see an actively maintained  MQTT client. Please squash my commits before merging, I tend to commit often but don't want to pollute the project.

I'm fairly new to Elixir but I'm starting to use this library for a Nerves project. If you have time to review, I'll continue to add tests as I make changes. Also, I'm happy to add some additional docs before the next release and update the readme to reflect the limited tests. If you're comfortable with even some of the low level tests being written in Elixir, I can add some coverage there.

The areas that I'll look at improving are:
- Auto disconnect if missing PingResp
- Availability of explicit Disconnect action for clean disconnect

2017-04-14 17:35 UTC, ericr3r reviewed
@asabil Please review the changes I made and let me know if there is anything remaining or you want me to rebase and squash in a new pull request.

2017-04-18 20:54 UTC, asabil commented
@erauer thanks again for the help and very sorry for the delayed answer.

Your help with erlang-mqtt is very much appreciated, and I would love to see some more documentation and tests go in before the next release. I think we can start by having the tests in Elixir if that is what you are most comfortable with, with the goal of hopefully moving these tests one layer below into Erlang land.

2017-04-18 21:06 UTC, asabil requested changes

2017-04-18 21:06 UTC, asabil commented on lib/mqtt/client.ex
> +      def init([]) do
I think this default implementation should be completely removed. I can't think of any valid use case where you wouldn't want to implement the `init` callback

2017-04-18 21:06 UTC, asabil commented on lib/mqtt/client.ex
> +      def handle_info(msg, state) do
Can we move the `handle_info` below the `handle_cast` ? This is the standard OTP callback order

2017-04-18 21:06 UTC, asabil commented on lib/mqtt/client.ex
> +      defoverridable [init: 1, handle_connect: 2, handle_connect_error: 2,
Same as above, `init` should be removed from this list.

2017-04-18 21:06 UTC, asabil commented on src/mqtt_client.erl
> -    Host = maps:get(host, Opts, "localhost"),
Actually I think this should be moved even below into `mqtt_transport`.

Today we have
`mqtt_transport:host() :: inet:ip_address() | inet:hostname().`

If we extend it to be
`mqtt_transport:host() :: inet:ip_address() | inet:hostname() | binary().`

Then we will just need to add a clause where we handle the binary case in `mqtt_transport:open/4` and `mqtt_transport:open/5`.

2017-04-19 20:55 UTC, asabil commented on src/mqtt_transport.erl
> +    open_tcp(unicode:characters_to_list(Host), Port, Options, Timeout);
I think this should be
`open(Protocol, unicode:characters_to_list(Host), Port, Options, Timeout);`

2017-04-19 23:18 UTC, erauer commented on src/mqtt_transport.erl
> +    open_tcp(unicode:characters_to_list(Host), Port, Options, Timeout);
good catch, this would have definitely broken SSL connections when hostname is binary. Updated in the pull request

2017-04-20 09:28 UTC, asabil approved these changes

2017-04-20 09:29 UTC, merged

2017-04-20 09:30 UTC, asabil commented
Thank you very much @erauer and sorry it took longer than normal to get this merged.